# ReportDiscordPlus Plugin Configuration
#
# By Francies
#
# These settings are very important for the plugin to work

config_version: "6"

discord:
  enabled: true
  webhookUrl: "https://discord.com/api/webhooks/your_webhook_id/your_webhook_token"
  pingRoleID: "YOUR_DISCORD_PING_ROLE_ID"
  alert: ":warning: New report available! :warning:"
  title: ":hammer_pick: ReportDiscordPlus :hammer_pick:"
  embedColor: 65280 # Color RGB format
  fields:
    reporter: "Reporter"
    reported: "Reported"
    reason: "Reason"
    server: "Server"

# Report cooldown time in seconds
cooldown: 60  # If left empty, the default value will be 60 seconds

# Minimum and maximum length of the reason
reason:
  minLength: 10
  maxLength: 100

# Messages
messages:
  prefix: "&6&lReport&7&lDSPL"
  missingID: "{prefix} &cyou need to specify an id!"
  reportNotFound: "{prefix} &cA report with id {id} doesn't exist!"
  noPlayerMentioned: "{prefix} &cYou need to specify a player"
  usage: "{prefix} &cCorrect usage /report <user> <reason>"
  cannotReportPlayer: "{prefix} &cYou cannot report this player."
  missingReason: "{prefix} &cYou must specify a reason for the report."
  cooldownMessage: "{prefix} &cYou have to wait &9{timeRemaining} &cseconds before you can send a new report."
  reportSent: "{prefix} &aYour report has been sent successfully!"
  noPermission: "{prefix} &cYou do not have permission to run this command."
  consoleCommand: "{prefix} &cThis command can only be performed by a player."
  myself: "{prefix} &cYou cannot report yourself!"
  usageClose: "{prefix} &cUsage: /rpclose close <id>"
  usageReopen: "{prefix} &cUsage: /rpreopen reopen <id>"
  reportReopened: "{prefix} &aReport {id} has been reopened."
  reportClosed: "{prefix} &aReport {id} has been closed."
  onlinePlayer: "{prefix} &cThis player is not online"
  usageDelete: "{prefix} &cUsage: /rpdelete delete <id>"
  reportDeleted: "{prefix} &aReport {id} has been deleted."
  invalidPageNumber: "{prefix} &cInvalid page number."
  reportListItem: "{prefix} &7- &eReport {id}: {reporter} -> {reported} ({reason}) [Status: {status}]"
  reportListHeader: "{prefix} &6&lOpen Reports (Page {page}/{totalPages}):"
  noReportsFound: "{prefix} &cNo report found."
  errorListingReports: "{prefix} &cError during listing reports."
  reasonTooShort: "{prefix} &cThe reason must contain at least {min} characters."
  reasonTooLong: "{prefix} &cThe reason cannot exceed {max} characters."
  staffAlert:
    - "&6&lNew report available!"
    - "&6Player: &9{player}"
    - "&6- Reported Player: &9{reportedPlayer}"
    - "&6- Reason: &9{reason}"
    - "&6- Server: &9{server}"
  openReportsMessage:
    - "&6Hi {player},"
    - "&6There are {amount} opened reports"

title: "&6&lNEW REPORT FROM {player}"
subtitle: "&9{reportedPlayer} has been reported for {reason} on {server}"

# this works only for Bungeecord proxy
button:
  show_text_server_button: "&bTeleport to the server"
  show_text_tp_button: "&bTeleport to the reported player"
  teleport_to_server: "&6TP-SERVER"
  teleport_to_player: "&aTP-PLAYER"
  separator: "&6&l-"

# Only seen by admins
updateMessage:
  - "&c&l[&6&lRDPLUS&c&l]&r &eUna nuova versione di &9ReportDiscordPlus &eè disponibile!"
  - "&eVersione corrente: &f{currentVersion} &7| &eNuova versione: &f{latestVersion}"
  - "&bLink per il download: &f{downloadUrl}"


