# ReportDiscordPlus Plugin Configuration
#
# By Francies
#
# These settings are very important for the plugin to work

config_version: "2"

discord:
  webhookUrl: "https://discord.com/api/webhooks/your_webhook_id/your_webhook_token"
  pingRoleID: "YOUR_DISCORD_PING_ROLE_ID"
  allert: ":warning: New report available! :warning:"
  title: ":hammer_pick: ReportDiscordPlus :hammer_pick:"
  reaction: "\uD83D\uDC4D"

# Report cooldown time in seconds
cooldown: 60  # If left empty, the default value will be 60 seconds

# Minimum and maximum length of the reason
reason:
  minLength: 10
  maxLength: 100

# Messages
messages:
  playerNotFound: "&6&lReport&7&lDSPL &cPlayer not found."
  onlineplayer: "&6&lReport&7&lDSPL &cThis player is not online"
  cannotReportPlayer: "&6&lReport&7&lDSPL &cYou cannot report this player."
  missingReason: "&6&lReport&7&lDSPL &cYou must specify a reason for the report."
  cooldownMessage: "&6&lReport&7&lDSPL &cYou have to wait &9{timeRemaining} &cseconds before you can send a new report."
  reportSent: "&6&lReport&7&lDSPL &aYour report has been sent successfully!"
  noPermission: "&6&lReport&7&lDSPL &cYou do not have permission to run this command."
  consoleCommand: "&6&lReport&7&lDSPL &cThis command can only be performed by a player."
  staffAlert: "&6&lReport&7&lDSPL &6&lNew report available!&r &6Player: &9{player} &6- Reported Player: &9{reportedPlayer} &6- Reason: &9{reason} &6- Server: &9{server}"
  myself: "&6&lReport&7&lDSPL &cYou cannot report yourself!"
  usageClose: "&cUsage: /rpclose close <id>"
  usageReopen: "&cUsage: /rpreopen reopen <id>"
  reportReopened: "&aReport {id} has been reopened."
  reportClosed: "&aReport {id} has been closed."
  usageDelete: "&cUsage: /rpdelete delete <id>"
  reportDeleted: "&aReport {id} has been deleted."
  invalidPageNumber: "&cInvalid page number."
  reportListItem: "&7- &eReport {id}: {reporter} -> {reported} ({reason}) [Status: {status}]"
  reportListHeader: "&6&lOpen Reports (Page {page}/{totalPages}):"
  noReportsFound: "&cNessun report trovato."
  errorListingReports: "&cError during listing reports."
  openReportsMessage: "&aThere are {amount} reports open."
  reasonTooShort: "&cThe reason must contain at least {min} characters."
  reasonTooLong: "&cThe reason cannot exceed {max} characters."


title: "&6&lNEW REPORT FROM {player}"
subtitle: "&9{reportedPlayer} has been reported for {reason} on {server}"

button:
  show_text_server_button: "&bTeleport to the server"
  show_text_tp_button: "&bTeleport to the reported player"
  teleport_to_server: "&6TP-SERVER"
  teleport_to_player: "&aTP-PLAYER"
  separator: "&6&l-"

updateMessages:
  header: "&c&l[&6&lRDPLUS&c&l]&r &eA newer version of &9ReportDiscordPlus &eis available!"
  versionMessage: "&c&l[&6&lRDPLUS&c&l]&r &eCurrent version: &f{currentVersion} &7| &eNew version: &f{latestVersion}"
  downloadMessage: "&c&l[&6&lRDPLUS&c&l]&r &bDownload link: &f{downloadUrl}"

